program: train.py
method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  num_filters:
    values: [32, 64]
  activation:
    values: ['ReLU', 'GELU', 'SiLU', 'Mish']
  filter_organisation:
    values: ['same', 'double', 'half']
  data_augmentation:
    values: [True, False]
  use_batchnorm:
    values: [True, False]
  dropout_rate:
    values: [0.0, 0.2, 0.3]
  batch_size:
    values: [32, 64]
  lr:
    min: 0.00001
    max: 0.001
  max_epochs:
    value: 10