method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  lr:
    min: 0.00001
    max: 0.001
  num_filters:
    values: [16, 32, 64]
  num_conv_layers:
    values: [3, 4, 5]
  kernel_size:
    values: [3, 5]
  activation:
    values: ['ReLU', 'GELU', 'SiLU', 'Mish']
  dense_neurons:
    values: [64, 128, 256]
  batch_size:
    values: [32, 64]
  max_epochs:
    value: 10

command:
  - ${env}
  - python
  - scripts/train.py
