method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  num_filters:
    values: [32, 64]
  activation:
    values: ['ReLU', 'GELU', 'SiLU', 'Mish']
  filter_organisation:
    values: ['same', 'double', 'half']
  data_augmentation:
    values: [True, False]
  use_batchnorm:
    values: [True, False]
  dropout_rate:
    values: [0.0, 0.2, 0.3]
  batch_size:
    values: [32, 64]
  lr:
    min: 0.00001
    max: 0.001
  max_epochs:
    value: 10

command:
  - ${env}
  - python
  - train.py
  - "--num_filters=${num_filters}"
  - "--activation=${activation}"
  - "--filter_organisation=${filter_organisation}"
  - "--batch_size=${batch_size}"
  - "--lr=${lr}"
  - "--max_epochs=${max_epochs}"
  - "--dropout_rate=${dropout_rate}"
  - ${args_no_boolean_flags}
  - ${data_augmentation}
  - ${use_batchnorm}
